---

Resources:



  WebServerSG:

    Type: AWS::EC2::SecurityGroup

    Properties:

      GroupDescription: SecurityGroup for WebServers 

      GroupName: WebServerFirewall

      SecurityGroupIngress:

        - CidrIp: 0.0.0.0/0

          Description: Allow any source from accessing port 80

          IpProtocol: tcp

          FromPort: 80

          ToPort: 80
      VpcId: !ImportValue CompanyVPC 



  DatabaseSG:

    Type: AWS::EC2::SecurityGroup

    Properties:

      GroupDescription: SecurityGroup For Databases

      GroupName: DatabaseFirewall

      SecurityGroupIngress:

        - SourceSecurityGroupId: !GetAtt WebServerSG.GroupId

          IpProtocol: -1

          ToPort: -1

          FromPort: -1
      VpcId: !ImportValue CompanyVPC        

        

Outputs: 

  WebServerSG:

    Description: SecurityGroup for WebServers

    Value: !Ref WebServerSG

    Export: 

      Name: WebServerSG

  DatabaseSG: 

    Description: SecurityGroup for Databases

    Value: !Ref DatabaseSG

    Export:

      Name: DatabaseSG
