---

Resources:

  CompanyVPC:

    Type: AWS::EC2::VPC 

    Properties:

      CidrBlock: 10.0.0.0/16

      EnableDnsHostnames: true

      EnableDnsSupport: true

      InstanceTenancy: default

      Tags:

        - Key: CompanyName

          Value: Company A

        - Key: Engineer

          Value: Rogmer Bulaclac



  InternetGateway:

    Type: AWS::EC2::InternetGateway

    Properties:

      Tags:

        - Key: Name

          Value: InternetGateway 
  GatewayAttachVPC:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref CompanyVPC 

  PublicRT:

    Type: AWS::EC2::RouteTable

    Properties:

      VpcId: !Ref CompanyVPC 


  PublicRoute:

     Type: AWS::EC2::Route

     DependsOn: 

      - PublicRT

      - InternetGateway

     Properties:

       RouteTableId: !Ref PublicRT 

       DestinationCidrBlock: 0.0.0.0/0

       GatewayId: !Ref InternetGateway



  PublicSubnet01:

    Type: AWS::EC2::Subnet 

    Properties:

      CidrBlock: 10.0.1.0/24

      AvailabilityZone: us-east-2a

      MapPublicIpOnLaunch: true

      Tags:

        - Key: Name 

          Value: PublicSubnet01

      VpcId: !Ref CompanyVPC

  

  PublicSubnet01RouteTableAssociation:

    Type: AWS::EC2::SubnetRouteTableAssociation

    DependsOn:

      - PublicRT

      - PublicSubnet01

    Properties:

      RouteTableId: !Ref PublicRT

      SubnetId: !Ref PublicSubnet01

  

  PublicSubnet02:

    Type: AWS::EC2::Subnet

    Properties:

      CidrBlock: 10.0.2.0/24

      AvailabilityZone: us-east-2b

      MapPublicIpOnLaunch: true

      Tags: 

        - Key: Name

          Value: PublicSubnet02

      VpcId: !Ref CompanyVPC



  PublicSubnet02RouteTableAssociation:

    Type: AWS::EC2::SubnetRouteTableAssociation

    DependsOn: 

      - PublicRT

      - PublicSubnet02

    Properties:

      RouteTableId: !Ref PublicRT

      SubnetId: !Ref PublicSubnet02



  PrivateSubnet01:

    Type: AWS::EC2::Subnet

    Properties:

      CidrBlock: 10.0.100.0/24

      AvailabilityZone: us-east-2c

      MapPublicIpOnLaunch: false

      Tags:

        - Key: Name

          Value: PrivateSubnet01 

      VpcId: !Ref CompanyVPC



Outputs:
  NetworkId:
    Description: Network VPC VpcId
    Value: !Ref CompanyVPC
    Export:
      Name: CompanyVPC

  NetworkAddress:

    Description: Network Address of CompanyA 

    Value: !GetAtt CompanyVPC.CidrBlock

  PublicSubnetGroup1:

    Description: IP Address Block for WebServer Group1

    Value:  !Ref PublicSubnet01

    Export:

      Name:  WebServerGroup1

  PublicSubnetGroup2:

    Description: IP Address Block for WebServer Group2

    Value:  !Ref PublicSubnet02

    Export:

      Name:  WebServerGroup2

  DatabaseGroup1:

    Description: IP Address Block for Databases

    Value:  !Ref PrivateSubnet01

    Export:

      Name:  DatabaseGroup1
